language: python
python:
    - 2.7
    - 3.6
install:
    - pip install flake8
script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=92 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
