name: Deploy MkDocs to GitHub Pages


on:
  push:
    branches:
      - main                # Trigger on pushes (including merges) into main
  # pull_request:
  #   branches:
  #     - main                # Trigger on PRs opened or updated against main


jobs:
  build:
    runs-on: ubuntu-latest
    # Only run on pull_request events
    if: github.event_name == 'pull_request'
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-static-i18n


      - name: ğŸ”¨ Build MkDocs site
        run: mkdocs build

  deploy:
    runs-on: ubuntu-latest
    # Only run on push events (so PRs wonâ€™t auto-deploy)
    if: github.event_name == 'push'
    needs: build
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-static-i18n

      - name: ğŸš€ Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
